### ISSUE TITLE
Couldn't connect to xxx:55000

### ISSUE THREAD

**Issue by e1z0** [Backgammonian/Decentralized-Chat-Peer#23]
I have started udp tracker server on separate machine, but i'm unable to connect to it from client, the traffic is passing ok (checked it with tcpdump)  but shows "Couldn't connect to xxx:55000".

**Comment by Backgammonian** [comment]
fixed

**Comment by e1z0** [comment]
I can confirm it is working now, but there are more problems that i have noticed, i don't know all the features that should work and which are not implemented yet but i have noticed that the "Connected peers" list is empty, i have connected two clients to the same tracker server, server shows Current number of users: 2, but in the client app the list is empty, also when i try to send text message i receive "Unrecognized command: 'Hello '". Thanks in advance!

**Comment by Backgammonian** [comment]
Tracker recognizes several commands from peers, one of them is 'connect'. You can just write 'connect [Nickname]' to tracker and it will connect you to peer with [Nickname]. Nicknames are case sensitive btw
